name: MellonDesigns
favicon: null
layout_spectrum: 0.9263137194793671
typography_spectrum: 0.47778959898278117
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7907469493802637
  lightness: 0.34290835238061845
  saturation: 0.9500891987700015
  rhythmicContrast: 0.06277601723559201
purpose: []
